### PR TITLE
Andriod intent edited and static sim slection removed

### PR DESCRIPTION
**Pull request by taufiqelahi**
The updated implementation of the DirectCaller class removes the SIM slot selection functionality, simplifying the code. The makePhoneCall method now:

**Simplified Calling Process**: Removed the optional parameter simSlot to focus on the default calling behavior without specifying a SIM slot. This makes the function more straightforward and easier to use.

**Specified Package Name**: Added the package: 'com.android.phone' argument to the AndroidIntent, which specifies the package name for the Android phone app. This change improves the reliability of launching the correct phone dialer app across different Android devices.

**Maintained Platform Check**: Retained the platform check to ensure that the intent is only launched on Android devices.

Overall, the contribution simplifies the functionality of the DirectCaller class and improves compatibility by specifying the package name for the Android phone app, making it more robust across various Android versions and devices.

### CODE REVIEW

**Comment by kuromadara** [comment]
hey thanks for the change. Did you test it, I'll not be testing if you did let me know I'll merge this.

**Comment by taufiqelahi** [comment]
I have checked the changes, and everything seems fine. However, I would appreciate it if you could also test this on your end. If you find any issues or think any updates are needed, please let me know, and I will make the necessary adjustments. Thanks!

**Comment by kuromadara** [comment]
okay I'll check it when i get time . For now I'm merging it.

**Comment by taufiqelahi** [comment]
Thanks for merging. I have also tested this GitHub repository in my project, and it works fine.

**Pull request merged**
